title: "Jekyll Actions Demo"
description: "Website Description"
baseurl: "/demo"
url: "https://scholarn.github.io"

theme: minimal-mistakes-jekyll
codeminimal_mistakes_skin: "dark"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
