title: "Jekyll Actions Demo"
description: "Website Description"
baseurl: "/demo"
url: "https://scholarn.github.io"
#theme: minima
header_pages:
  - about.md

defaults:
  - scope:
      path: ""  # Applies to all pages
    values:
      layout: "page"

  # Apply to all posts
  - scope:
      path: ""  # Applies to all posts
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
