title: "Jekyll Actions Demo"
description: "Website Description"
baseurl: "/demo"
url: "https://scholarn.github.io"

header_pages:
  - about.md
theme: minimal-mistakes-jekyll
defaults:
  # Apply to all posts
  - scope:
      path: ""  # Applies to all posts
      type: "posts"
    values:
      layout: "post"

  - scope:
      path: ""  # Applies to all pages
      type: "pages"
    values:
      layout: "page"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
