title: "Jekyll Actions Demo"
description: "Website Description"
baseurl: ""
url: "https://test.scholarn.com"
#theme: minima
header_pages:
  - about.md
remote_theme: scholarn/glint
defaults:
  - scope:
      path: ""  # Applies to all pages
    values:
      layout: "page"

  # Apply to all posts
  - scope:
      path: ""  # Applies to all posts
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
