title: "Jekyll Actions Demo"
description: "Website Description"
baseurl: "/demo"
url: "https://scholarn.github.io"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
# Enable theme skin switcher in the site footer.
skin_switcher: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
