name: Jekyll site CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to manually trigger the workflow from GitHub Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v2

    # Set up Ruby
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Specify your Ruby version

    # Install dependencies
    - name: Install dependencies
      run: |
        bundle install

    # Build the Jekyll site
    - name: Build Jekyll site
      run: |
        bundle exec jekyll build

    # Deploy the site to GitHub Pages (only on push to main branch)
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
